gear_shop/urls.py
from store.views import LandingPageView, SignupView
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    # parent store url
    path('store/',include('store.urls', namespace='store')),

    # landing page
    path('', LandingPageView.as_view(), name='landing_page'),

    # sign in and sign up
    path('sign_in/', LoginView.as_view(), name='sign_in_page'),
    path('sign_up/', SignupView.as_view(), name='sign_up_page'),
    path('logout/', LogoutView.as_view(), name='log_out_page'),
    
    # password reset flow urls
    path('password-reset/', PasswordResetView.as_view(), name='password_reset_view'),
    path('passowrd_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('passowrd_reset_complete/', PasswordResetCompleteView.as_view(), name='passowrd_reset_complete'),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from store.views import AllProductView, CartView, CheckoutView, LandingPageView, NewArrivalsView, PopularItemsView, ProcessOrder, SignupView, UpdateItem
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

app_name = 'store'
urlpatterns = [
    # store navigation urls
    path('products/',AllProductView.as_view(), name='all_products_page'),
    path('popular_items/',PopularItemsView.as_view(), name='popular_items_page'),
    path('new_arrivals/',NewArrivalsView.as_view(), name='new_arrivals_page'),
    path('cart/',CartView.as_view(), name='cart_page'),
    path('checkout/',CheckoutView.as_view(), name='checkout_page'),
    path('update_item/', UpdateItem.as_view(), name='update_item'),
    path('process_order/', ProcessOrder.as_view(), name='process_order'),
]

store/models.py
from django.db import models
from django.db.models.signals import post_save


# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE, DO_NOTHING, SET_NULL

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE, null=True, blank=True)
    # name = models.CharField(max_length=200, null=True, blank=True)
    # email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.user.email

class ProductCategory(models.Model):
    category = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.category)

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    current_price = models.DecimalField(max_digits=7, decimal_places=2, default=0, null=True, blank=True)
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    popular = models.BooleanField(default=False, null=True, blank=True)
    new_arrival = models.BooleanField(default=False, null=True, blank=True)
    discount_offer = models.BooleanField(default=False, null=True, blank=True)
    old_price = models.DecimalField(max_digits=7, decimal_places=2, default=0, null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        if self.image:
            return self.image.url
        return '/images/no-image.jpg'
    
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=200, null=True, blank=True)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
                break
        return shipping
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        quantity = sum([item.quantity for item in orderitems])
        return quantity

    def __str__(self):
        return self.customer.user.email

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateField(auto_now_add=True, null=True, blank=True)

    @property
    def get_total(self):
        total = self.quantity * self.product.current_price
        return total

    def __str__(self):
        return self.order.customer.user.email

class ShippigAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=DO_NOTHING, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=CASCADE, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=200, null=True, blank=True)
    state = models.CharField(max_length=200, null=True, blank=True)
    zipcode = models.CharField(max_length=200, null=True, blank=True)
    date_added = models.DateField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.address


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        Customer.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

store/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm, UsernameField


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

store/views.py
from django.views.generic.base import View
from store.models import Customer, Order, OrderItem, Product, ShippigAddress
from typing import Generic
from django.shortcuts import render, resolve_url, reverse
from django.views import generic
from .forms import CustomUserCreationForm
from django.http import JsonResponse, request
import json
import datetime
from .utils import get_items_order_cartItems, geustOrder

# Create your views here.
class LandingPageView(generic.TemplateView):
    template_name = 'landing.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'cartItems': (get_items_order_cartItems(self.request))['cartItems']
        })
        return context

class SignupView(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm

    def get_success_url(self) -> str:
        return reverse("sign_in_page") 

class AllProductView(generic.ListView):
    template_name = 'store/products.html'
    context_object_name = 'products'
    queryset = Product.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'cartItems': (get_items_order_cartItems(self.request))['cartItems']
        })
        return context

class PopularItemsView(generic.TemplateView):
    template_name = 'store/products.html'
    queryset = Product.objects.filter(popular=True)
    # print(queryset)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            customer = self.request.user.customer
            order, created = Order.objects.get_or_create(customer=customer, complete=False)
            cartItems = order.get_cart_items
        else:
            cartItems = 0
        context.update({
            'products': self.queryset,
            'cartItems': (get_items_order_cartItems(self.request))['cartItems']
        })
        return context

class NewArrivalsView(generic.TemplateView):
    template_name = 'store/products.html'
    queryset = Product.objects.filter(new_arrival=True)
    # print(queryset)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            customer = self.request.user.customer
            order, created = Order.objects.get_or_create(customer=customer, complete=False)
            cartItems = order.get_cart_items
        else:
            cartItems = 0
        context.update({
            'products': self.queryset,
            'cartItems': (get_items_order_cartItems(self.request))['cartItems']
        })
        return context

class CartView(generic.TemplateView):
    template_name = 'store/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_items_order_cartItems(self.request))
        return context

class CheckoutView(generic.TemplateView):
    template_name = 'store/checkout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_items_order_cartItems(self.request))
        return context

class UpdateItem(View):
    def post(self, request):
        if request:
            data = json.loads(request.body)
            productID = data['productID']
            action = data['action']

            customer = request.user.customer
            product = Product.objects.get(id=productID)
            order, created = Order.objects.get_or_create(customer=customer, complete=False)

            orderitem, created = OrderItem.objects.get_or_create(order=order, product=product)
            if action == 'add':
                orderitem.quantity = orderitem.quantity + 1
            elif action == 'remove':
                orderitem.quantity = orderitem.quantity - 1
            orderitem.save()

            if orderitem.quantity <= 0:
                orderitem.delete()

            return JsonResponse("Item", safe=False)

class ProcessOrder(View):
    def post(self, request):
        if request:
            data = json.loads(request.body)
            transaction_id = datetime.datetime.now().timestamp()

            if self.request.user.is_authenticated:
                customer = self.request.user.customer
                order, created = Order.objects.get_or_create(customer=customer, complete=False)    
            else:
                customer, order = geustOrder(self.request, data)

        total =  float(data['form']['total'])
        order.transaction_id = transaction_id

        if total == float(order.get_cart_total):
            order.complete = True
        order.save()

        if order.shipping == True:
            ShippigAddress.objects.create(
                customer = customer,
                order = order,
                address = data['shipping']['address'],
                city = data['shipping']['city'],
                state = data['shipping']['state'],
                zipcode = data['shipping']['zipcode'],
            )

        return JsonResponse("Item", safe=False)

store/templates/store/cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="py-5">
  <div class="container container-sm px-4 px-lg-5 local-table-container">
      <table class="table table-sm table-bordered table-hover table-light table-responsive col-form-label-sm local-table-1">
          <thead>
            <tr>
              <th scope="col" colspan="2" class="text-align-center"></th>
              <th scope="col" class="text-align-center">Item</th>
              <th scope="col" class="text-align-center">Price</th>
              <th scope="col" class="text-align-center">Quantity</th>
              <th scope="col" class="text-align-center">Total Price</th>
            </tr>
          </thead>
          <tbody>
            {% for item in items %}
            <tr>
              <td colspan="2" class="text-align-center"><img src="{{ item.product.imageURL }}" class="cart-product-icon"></td>
              <td class="text-align-center">{{item.product.name}}</td>
              <td class="text-align-center">&#x20B9;. {{item.product.current_price}}</td>
              <td class="text-align-center">
                <span class="quantity">{{ item.quantity }}</span>
                <div class="quantity">
                  <img src="{% static 'images/up.png' %}" data-product="{{item.product.id}}" data-action="add" alt="" class="chg-quantity update-cart">
                  <img src="{% static 'images/down.png' %}" data-product="{{item.product.id}}" data-action="remove" alt="" class="chg-quantity update-cart">
                </div>
              </td>
              <td class="text-align-center">&#x20B9;. {{item.get_total}}</td>
            </tr> 
            {% endfor %}  
          </tbody>
      </table>   
      <table class="table table-sm table-light table-responsive table-bordered local-table-2">
        <tbody>
          <tr>
            <td><strong>Items:</strong></td>
            <td class="text-align-right"><strong>{{order.get_cart_items}}</strong></td>
          </tr>
          <tr>
            <td><strong>Price:</strong></td>
            <td class="text-align-right"><strong>&#x20B9;. {{order.get_cart_total}}</strong></td>
          </tr>
          <tr>
            <td></td>
            <td class="text-align-right"><a href="{% url 'store:checkout_page' %}" class="btn btn-success checkout-btn" id="checkout-btn1"><strong>CHECKOUT</strong></a></td>
          </tr>
          <tr>
            <td></td>
            <td class="text-align-right"><a href="{% url 'store:all_products_page' %}" class="btn btn-outline-dark continue-shopping-btn">&#x2190; Continue Shopping</a></td>
          </tr> 
        </tbody>
    </table> 
    <div class="break"></div> <!-- break -->
    
  </div>
  
</section>

<script type="text/javascript">
  window.onload=function() {
    var quantity = '{{order.get_cart_items}}'
    console.log(typeof(quantity))
    if (quantity <= 0){
      console.log(typeof(quantity))
      document.getElementById("checkout-btn1").classList.add('disabled-link')
    }
  }
  
</script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
{% endblock content %}

store/templates/store/checkout.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                <form id="form" action="">
                    {% csrf_token %}
                    <div id="user-info">
                        <div class="form-floating mx-sm-2">
                            <input required type="text" class="form-control" id="floatingname" name="name" placeholder="">
                            <label for="floatingInput">Username</label>
                        </div>
                        <div class="form-floating">
                            <input required type="email" class="form-control" id="floatingemail" name="email" placeholder="">
                            <label for="floatingPassword">Email address</label>
                        </div>
                        
                    </div>
                    <hr>
                    <h5  id="shipping-info-header">Shipping Info:</h5>
                    <div id="shipping-info">
                        <div class="form-floating mx-sm-2 mb-2">
                            <input required type="text" class="form-control" id="floatingaddress" name="address" placeholder="">
                            <label for="floatingInput">Address</label>
                        </div>
                        <div class="form-floating mb-2">
                            <input required type="text" class="form-control" id="floatingcity" name="city" placeholder="">
                            <label for="floatingPassword">City</label>
                        </div>
                        <div class="form-floating mx-sm-2 mb-2">
                            <input required type="text" class="form-control" id="floatingstate" name="state" placeholder="">
                            <label for="floatingInput">State</label>
                        </div>
                        <div class="form-floating mb-2">
                            <input required type="text" class="form-control" id="floatingzipcode" name="zipcode" placeholder="">
                            <label for="floatingPassword">Zipcode</label>
                        </div>
                        <hr>
                    </div>
                    
                    <input class="btn btn-success btn-block px-6 continue-checkout-button" type="submit" id="form-button" value="Continue">
                </form>
            </div>

            <br>

            <div class="box-element hidden" id="payment-info">
                <h5>Payment Options</h5>
                <button id="make-payment">Make Payment</button>
            </div>
        </div>

        <div class="col-lg-6">
            
            <div class="box-element">
                <a href="{% url 'store:cart_page' %}" class="btn btn-outline-dark back-cart-button">&#x2190; Back To Cart</a>
                <hr>

                <h5>Order Summary:</h5>
                <table class="table table-xl table-bordered table-hover table-light table-responsive col-form-label-sm local-table-3">
                    <thead>
                      <tr>
                        <th scope="col" class="text-align-center">Item</th>
                        <th scope="col" class="text-align-center">Price</th>
                        <th scope="col" class="text-align-center">Quantity</th>
                        <th scope="col" class="text-align-center">Total Price</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for item in items %}
                        <tr>
                          <td class="text-align-center">{{item.product.name}}</td>
                          <td class="text-align-center">&#x20B9;. {{item.product.current_price}}</td>
                          <td class="text-align-center">{{ item.quantity }}</td>
                          <td class="text-align-center">&#x20B9;. {{item.get_total}}</td>
                        </tr> 
                        {% endfor %}  
                    </tbody>
                </table> 
                <table class="table table-sm table-light table-responsive local-table-4">
                    <tbody>
                      <tr>
                        <td><strong>Total Items:</strong></td>
                        <td class="text-align-right"><strong>{{order.get_cart_items}}</strong></td>
                      </tr>
                      <tr>
                        <td><strong>Total Price:</strong></td>
                        <td class="text-align-right"><strong>&#x20B9;. {{order.get_cart_total}}</strong></td>
                      </tr>
                      <!-- <tr>
                        <td></td>
                        <td class="text-align-right"><a href="{% url 'store:checkout_page' %}" class="btn btn-success checkout-btn"><strong>CHECKOUT</strong></a></td>
                      </tr>
                      <tr>
                        <td></td>
                        <td class="text-align-right"><a href="{% url 'landing_page' %}" class="btn btn-outline-dark continue-shopping-btn">&#x2190; Continue Shopping</a></td>
                      </tr>  -->
                    </tbody>
                </table> 
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var shipping = '{{order.shipping}}'
        var total = '{{order.get_cart_total}}'

        if(shipping == 'False'){
            document.getElementById('shipping-info').innerHTML = ''
            document.getElementById('shipping-info-header').innerHTML = ''
        }

        if (user_logged != 'AnonymousUser'){
            document.getElementById('user-info').innerHTML = ''
        }

        if (shipping == 'False' && user_logged != 'AnonymousUser'){
            document.getElementById('form-wrapper').classList.add('hidden')
            document.getElementById('payment-info').classList.remove('hidden')
        }



        var form = document.getElementById('form')
        form.addEventListener('submit', function(e){
            e.preventDefault()
            // console.log('form submit')
            document.getElementById('form-button').classList.add('hidden')
            document.getElementById('payment-info').classList.remove('hidden')
        })

        


        document.getElementById('make-payment').addEventListener('click', function(e){
            submitFormData()
        })

        function submitFormData(){
            console.log('payment button clicked')

            

            var userFormData = {
                'name': null,
                'email': null,
                'total': total,
            }

            var shippingInfo = {
                'address': null,
                'city': null,
                'state': null,
                'zipcode': null,
            }

            if(shipping != 'False'){
                shippingInfo.address = form.address.value
                shippingInfo.city = form.city.value
                shippingInfo.state = form.state.value
                shippingInfo.zipcode = form.zipcode.value
            }

            if(user_logged == 'AnonymousUser'){
                userFormData.name = form.name.value
                userFormData.email = form.email.value
            }

            var url = '/store/process_order/'
            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({'form': userFormData, 'shipping': shippingInfo}),
            })
            .then((res) => res.json())
            .then((data) => {
                console.log(data);
                alert('Transx completed');
                cart = {}
                document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
                window.location.href = "{% url 'store:all_products_page' %}"
            })
        
        }

        
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
{% endblock content %}

store/templates/store/products.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="py-1">
    <div class="container container-xxl px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center local-row">
            <!-- div for normal products -->
            {% for product in products %}
                {% if not product.discount_offer %}
                    <div class="col local-col mb-5">
                        <div class="card local-card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{product.imageURL}}" alt="{{product.name}}" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><a href="#" style="text-decoration: none;">{{product.name}}</a></h5>
                                    <!-- Product price-->
                                    &#x20B9;. {{product.current_price}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><button class="btn btn-outline-dark mt-auto add-btn update-cart" href="#" data-product="{{product.id}}" data-action="add">Add to cart</button></div>
                            </div>
                        </div>
                    </div>
            
                {% else %}
                    <!-- div for sale -->
                    <div class="col local-col mb-5">
                        <div class="card local-card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{{product.imageURL}}" alt="{{product.name}}" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder"><a href="#" style="text-decoration: none;">{{product.name}}</a></h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through">&#x20B9. {{product.old_price}}</span>
                                        &#x20B9. {{product.current_price}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><button class="btn btn-outline-dark mt-auto add-btn update-cart" href="#" data-product="{{product.id}}" data-action="add">Add to cart</button></div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                
            {% endfor %}
        </div>
    </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js">
</script>
{% endblock content %}