gear_shop/urls.py
from store.views import LandingPageView, SignupView
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    # parent store url
    path('store/',include('store.urls', namespace='store')),

    # landing page
    path('', LandingPageView.as_view(), name='landing_page'),

    # sign in and sign up
    path('sign_in/', LoginView.as_view(), name='sign_in_page'),
    path('sign_up/', SignupView.as_view(), name='sign_up_page'),
    path('logout/', LogoutView.as_view(), name='log_out_page'),
    
    # password reset flow urls
    path('password-reset/', PasswordResetView.as_view(), name='password_reset_view'),
    path('passowrd_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('passowrd_reset_complete/', PasswordResetCompleteView.as_view(), name='passowrd_reset_complete'),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from store.views import AllProductView, CartView, CheckoutView, LandingPageView, NewArrivalsView, PopularItemsView, ProcessOrder, SignupView, UpdateItem
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

app_name = 'store'
urlpatterns = [
    # store navigation urls
    path('products/',AllProductView.as_view(), name='all_products_page'),
    path('popular_items/',PopularItemsView.as_view(), name='popular_items_page'),
    path('new_arrivals/',NewArrivalsView.as_view(), name='new_arrivals_page'),
    path('cart/',CartView.as_view(), name='cart_page'),
    path('checkout/',CheckoutView.as_view(), name='checkout_page'),
    path('update_item/', UpdateItem.as_view(), name='update_item'),
    path('process_order/', ProcessOrder.as_view(), name='process_order'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>G's Gear Shop</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/local.css' %}" rel="stylesheet" />
        <script>
            var user_logged = '{{request.user}}'

            function getToken(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    const cookies = document.cookie.split(';');
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
                
            }
            const csrftoken = getToken('csrftoken');


            function getCookie(name){
                var cookieArr = document.cookie.split(";");

                for(var i=0; i < cookieArr.length; i++){
                    var cookiePair = cookieArr[i].split("=");

                    if (name == cookiePair[0].trim()){
                        return decodeURIComponent(cookiePair[1]);
                    }
                }

                return null;
            }
            var cart = JSON.parse(getCookie('cart'))

            if (cart == undefined){
                cart = {}
                document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
                // console.log(cart)
            }
        </script>
    </head>
    <body>
            <!-- Navigation-->
            {% include "navbar.html" %}
            <!-- Header-->
            <header class="bg-blue py-2">
                <div class="container px-1 px-lg-1 my-1">
                    <div class="text-center text-white">
                        <h1 class="display-4 fw-bolder">G's Gear Shop</h1>
                        <p class="lead fw-normal text-white-50 mb-0">You Ask, We Deliver.</p>
                    </div>
                </div>
            </header>
            
            <!-- Section-->
            {% block content %}
            
            {% endblock content %}
         
       <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/landing.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<section class="py-5" style="width: 100%;">
    <div class="container px-3 px-lg-5 mt-4">
        <h1>this landing page</h1>
        <h1>this landing page</h1>
        <h1>this landing page</h1>
        <h1>this landing page</h1>
        <h1>this landing page</h1>
        <h1>this landing page</h1>
    </div>
</section>
<!-- Footer-->
<footer class="py-5 bg-blue">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; ggs.com Website 2021</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

{% endblock content %}

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'landing_page' %}">G.G.S.</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'landing_page' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Support</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'store:all_products_page' %}">All Products</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{% url 'store:popular_items_page' %}">Popular Items</a></li>
                        <li><a class="dropdown-item" href="{% url 'store:new_arrivals_page' %}">New Arrivals</a></li>
                    </ul>
                </li>
                
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{user.username}}</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'store:all_products_page' %}">Profile Settings</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{% url 'log_out_page' %}">Log Out</a></li>
                    </ul>
                </li>
            
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'sign_up_page' %}">Sign Up</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'sign_in_page' %}">Sign In</a></li>
            
            {% endif %}
            </ul>
            <!-- <span>
                {% if user.is_authenticated %}
                  {{user.username}}
                {% endif %}
            </span> -->
            <form action="{% url 'store:cart_page' %}" class="d-flex">
                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    Cart
                    <span class="badge bg-white text-dark ms-1 rounded-pill">{{cartItems}}</span>
                </button>
            </form>
            </div>
        </div>
    </div>
</nav>